# Sesi 4 - NumPy
## Numpy Introduction
NumPy (Numerical Python) merupakan library/pustaka pada Python dan merupakan standar universal dalam pengerjaan dengan data numerik pada Python, serta merupakan inti dari ekosistem ilmiah Python dan PyData.
<br><br>
API NumPy meliputi Pandas, SciPy, MatPlotLib, dan lain-lain.

## Installing NumPy
`conda install numpy`
<br><br>
atau
<br><br>
`pip install numpy`

## How to Import NumPy

In [1]:
import numpy as np

## Array

### Creating Array

`np.array()`
<br>
`np.zeros()`
<br>
`np.ones()`
<br>
`np.empty()`
<br>
`np.arange()`

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# Membuat array dengan nilai 0
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
# Membuat array dengan nilai 1
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
# Membuat array kosong
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
# Membuat array dengan range elemen tertentu
print(np.arange(4))
print(np.arange(0, 10, 2)) # (batas awal, stop, kelipatan)

[0 1 2 3]
[0 2 4 6 8]


In [7]:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

### Add, Remove, and Sort

`np.append()`
<br>
`np.delete()`
<br>
`np.sort()`

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [9]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size
`ndarray.ndim()` akan memberitahu jumlah dimensi pada array
<br>
`ndarray.size()` akan memberitahu jumlah total elemen pada array
<br>
`ndarray.shape()` akan memberitahu luas dimensi array

In [11]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [12]:
array_example.ndim

3

In [13]:
array_example.size

24

In [14]:
array_example.shape

(3, 2, 4)

In [15]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [16]:
arr_one.ndim

2

In [17]:
arr_one.size

5

In [18]:
arr_one.shape

(1, 5)

### Reshape
`np.reshape()`

In [19]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [20]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [21]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert 1D to 2D
`np.newaxis`
<br>
`np.expand_dims`

In [22]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [23]:
a2 = a[np. newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [24]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [25]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [27]:
b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [28]:
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

### Indexing and Slicing

In [29]:
data = np.array([1, 2, 3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [30]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# print nilai pada array yang lebih dari sama dengan 5
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [32]:
five_up = (a >= 5)
print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [33]:
# print nilai pada array yang dapat dibagi 2
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [34]:
# menggunakan 2 kondisi dengan & (and) dan | (or)

c = a[(a > 2) & (a < 11)]
print(c)
d = a[(a < 5) | (a > 10)]
print(d)

[ 3  4  5  6  7  8  9 10]
[ 1  2  3  4 11 12]


### Creating Array from Existing Data
`slicing indexing`
<br>
`np.vstack()`
<br>
`np.hstack()`
<br>
`np.hsplit()`
<br>
`.view()`
<br>
`.copy()`

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [36]:
a_1 = np.array([[1, 1], 
             [2, 2]])
a_2 = np.array([[3, 3], 
             [4, 4]])

In [37]:
# Tumpuk secara vertikal
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [38]:
# Tumpuk secara horizontal
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [39]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [40]:
# Membagi array menjadi 3 array dengan shape yang sama
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [41]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic Array Operations
Addition, substraction, multiplication, division, and more
<br>
`data + ones`
<br>
`data - ones`
<br>
`data * ones`
<br>
`data / ones`

In [44]:
a = np.array([1, 2, 3, 4])

# Menjumlahkan semua nilai elemen pada array
a.sum()

10

In [45]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [46]:
# Menjumlahkan antar baris
b.sum(axis = 0)

array([3, 3])

In [47]:
# Menjumlahkan antar kolom
b.sum(axis = 1)

array([2, 4])

In [48]:
data = np.array([1, 2])
data

array([1, 2])

In [49]:
ones = np.ones(2)
ones

array([1., 1.])

In [50]:
data + ones

array([2., 3.])

In [51]:
data * data

array([1, 4])

In [52]:
data / data

array([1., 1.])

### Broadcasting
`data * 1.6`

In [53]:
data * 2

array([2, 4])

### More Array Operations
`Maximum`, `minimum`, `sum`, `mean`, `product`, `standard deviation`, dan lain-lain.
<br><br>
`data.max()`
<br>
`data.min()`
<br>
`data.sum()`

In [54]:
A = np.array([[0.45043315, 0.1729323, 1.932984, 0.2985853], 
              [0.98542941, 0.4422524, 0.120313, 1.2325134],
              [2.00039212, 1.2943958, 0.239877, 1.2838888]])
print(A)

[[0.45043315 0.1729323  1.932984   0.2985853 ]
 [0.98542941 0.4422524  0.120313   1.2325134 ]
 [2.00039212 1.2943958  0.239877   1.2838888 ]]


In [55]:
A.sum()

10.45399668

In [56]:
A.min()

0.120313

In [60]:
A.min(axis = 0)

array([0.45043315, 0.1729323 , 0.120313  , 0.2985853 ])

In [57]:
A.max()

2.00039212

In [61]:
A.max(axis = 1)

array([1.932984  , 1.2325134 , 2.00039212])

In [62]:
A.std()

0.6477119172584985

## Matrices

### Creating Matrices
`np.array([[1, 2], [3, 4]])`

In [65]:
np.ones((3, 2))
np.zeros((3, 2))
np.random.random((3, 2))

array([[0.97664321, 0.89171885],
       [0.40792069, 0.40780459],
       [0.93929256, 0.2038868 ]])

In [66]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(np.random.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.59955153 0.68024727]
 [0.49827206 0.71715969]
 [0.39397633 0.44660103]]


### Matrix Arithmetic

In [67]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [69]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [70]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [71]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [72]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product
`dot()`

In [73]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [74]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [75]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0, 1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation

In [76]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [77]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [78]:
print(data.max(axis = 0))
print(data.max(axis = 1))

[5 6]
[2 4 6]


### Transposing and Reshaping

In [79]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [80]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [81]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [82]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array

In [85]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [86]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [87]:
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [88]:
print(np.random.random((4, 3, 2)))

[[[0.16697581 0.95371462]
  [0.072697   0.19097851]
  [0.14331859 0.71900138]]

 [[0.63159938 0.69090993]
  [0.2057894  0.46778442]
  [0.36302911 0.11347828]]

 [[0.33792466 0.73376264]
  [0.82874751 0.69530114]
  [0.84585784 0.04418633]]

 [[0.85542091 0.74390403]
  [0.75538962 0.7810931 ]
  [0.4139999  0.73723778]]]


### Flatten N-Dimensional Array
2 cara populer meratakan array, yaitu: 
<br>
- `.flatten()`
<br>
- `.ravel()`

In [89]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [91]:
# Meratakan array ke dalam array 1 dimensi
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction))